const SB_URL=String(window.WILPATTU_SUPABASE_URL||'').replace(/\/+$/,'');
const SB_KEY=window.WILPATTU_SUPABASE_ANON_KEY||'';
let sb=null;
if(window.supabase?.createClient && SB_URL && SB_KEY){sb=window.supabase.createClient(SB_URL,SB_KEY);window.sbClient=sb}

const rates={morning:[150,120,100,90,85,80,90,85,80,80,80,80],evening:[150,120,100,90,85,80,90,85,80,80,80,80],full:[220,150,130,120,105,95,120,115,110,100,100,100]};
const labels={morning:'Half-Safari Morning',evening:'Half-Safari Evening',full:'Full Day Safari'};
function money(n){return '$'+Number(n).toFixed(0)}
function calc(type,count){const c=Math.max(1,Math.min(12,Number(count)||1));const pp=rates[type][c-1];return {count,pp,total:pp*c}}
function updatePricing(root=document){const type=root.querySelector('[data-price-type]')?.value;const count=root.querySelector('[data-passengers]')?.value;if(!type||!count)return;const x=calc(type,count);root.querySelector('[data-pp]').textContent=money(x.pp)+' / person';root.querySelector('[data-total]').textContent=money(x.total);if(root.querySelector('[data-rate-label]'))root.querySelector('[data-rate-label]').textContent=`${count} passenger${count==1?'':'s'} · ${labels[type]}`}
function bindPricing(){document.querySelectorAll('[data-pricing], [data-booking-form]').forEach(root=>{root.querySelectorAll('[data-price-type], [data-passengers]').forEach(el=>{el.addEventListener('change',()=>updatePricing(root));el.addEventListener('input',()=>updatePricing(root))});updatePricing(root)})}
function fillBooking(type,count){const p=new URLSearchParams({package:type,passengers:String(count||1)});location.href='booking.html?'+p.toString()}
function initNav(){const nav=document.querySelector('.site-nav');const menu=document.querySelector('.menu');const links=document.querySelector('.nav-links');window.addEventListener('scroll',()=>nav?.classList.toggle('scrolled',scrollY>30),{passive:true});menu?.addEventListener('click',()=>links?.classList.toggle('open'))}
function initReveal(){const els=document.querySelectorAll('.reveal');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});els.forEach(e=>io.observe(e))}
function initHeroParallax(){const bg=document.querySelector('.hero-bg');if(!bg)return;window.addEventListener('scroll',()=>{bg.style.transform=`scale(1.08) translateY(${Math.min(scrollY*.12,90)}px)`},{passive:true})}
function initStage(){const stage=document.querySelector('.story-stage');const bg=document.querySelector('.stage-bg');const animal=document.querySelector('.stage-animal');if(!stage||!bg||!animal)return;const tick=()=>{const r=stage.getBoundingClientRect();const p=Math.max(0,Math.min(1,(-r.top)/(stage.offsetHeight-innerHeight)));bg.style.transform=`scale(${1.05+p*.09}) translate3d(${p*-2}%,${p*-3}%,0)`;animal.style.opacity=Math.min(1,p*2);animal.style.transform=`translate3d(${15-p*24}%,${20-p*30}px,0) scale(${.92+p*.18})`};window.addEventListener('scroll',tick,{passive:true});tick()}
async function submitBooking(form){const msg=form.querySelector('.form-msg');const data=new FormData(form);const type=data.get('experience');const count=Number(data.get('guests')||1);const x=calc(type,count);const ref='WS-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,7).toUpperCase();const payload={reference:ref,experience:labels[type],safari_date:data.get('safari_date'),guests:count,pickup:data.get('pickup'),customer_name:data.get('customer_name'),whatsapp:data.get('whatsapp'),notes:`Email: ${data.get('email')||'—'} | Destination/transfer note: ${data.get('destination')||'—'} | Customer notes: ${data.get('notes')||'—'} | Estimated total: ${money(x.total)}`,status:'pending'};try{if(!sb)throw new Error('Booking service is not connected yet.');const {error}=await sb.from('safari_bookings').insert(payload);if(error)throw error;msg.className='form-msg success';msg.innerHTML=`Booking request received.<br><b>Reference: ${ref}</b><br>Per person: <b>${money(x.pp)}</b> · Group total: <b>${money(x.total)}</b>.<br><br><a class="btn gold" href="${buildWhatsAppUrl(payload,x)}" target="_blank" rel="noopener">Send booking to WhatsApp →</a>`;window.location.href=buildWhatsAppUrl(payload,x);return;const pt=form.querySelector('[data-price-type]');if(pt){pt.value=type;form.querySelector('[data-passengers]').value=count;updatePricing(form)} }catch(e){msg.className='form-msg error';msg.textContent=e.message||'Unable to submit booking.'}}
async function loadReviews(){const list=document.querySelector('[data-review-list]');if(!list||!sb)return;const {data}=await sb.from('traveller_stories').select('name,rating,comment,photo_path,created_at').eq('status','approved').order('created_at',{ascending:false}).limit(12);if(!data?.length){list.innerHTML='<div class="review-card"><b>Be one of our first storytellers.</b><p>After your safari, share your experience, rating and a photo with future travellers.</p></div>';return}list.innerHTML=data.map(x=>{const photo=x.photo_path?sb.storage.from('traveller-stories').getPublicUrl(x.photo_path).data.publicUrl:'';return `<article class="review-card">${photo?`<img src="${photo}" alt="Traveller photo" style="width:100%;max-height:230px;object-fit:cover;border-radius:14px;margin-bottom:15px">`:''}<div class="stars">${'★'.repeat(Number(x.rating)||0)}${'☆'.repeat(5-(Number(x.rating)||0))}</div><h3 style="margin-top:8px;font-size:24px">${escapeHtml(x.name)}</h3><p>${escapeHtml(x.comment)}</p></article>`}).join('')}
function buildWhatsAppUrl(payload,x){const wa=(window.WILPATTU_WHATSAPP||'94704658975').replace(/\D/g,'');const lines=['*NEW WILPATTU SAFARI BOOKING*','Reference: '+payload.reference,'Safari: '+payload.experience,'Date: '+payload.safari_date,'Guests: '+payload.guests,'Pickup: '+(payload.pickup||'—'),'Name: '+payload.customer_name,'WhatsApp: '+payload.whatsapp,'Estimated total: '+money(x.total),payload.notes];return 'https://wa.me/'+wa+'?text='+encodeURIComponent(lines.join('\n'))}
function escapeHtml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
async function submitReview(form){const msg=form.querySelector('.form-msg');const data=new FormData(form);try{if(!sb)throw new Error('Review service is not connected yet.');let photoPath=null;const file=data.get('photo');if(file&&file.size){if(file.size>6*1024*1024)throw new Error('Please keep the photo under 6 MB.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase();photoPath=`reviews/${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('traveller-stories').upload(photoPath,file,{upsert:false});if(up.error)throw up.error}const {error}=await sb.from('traveller_stories').insert({name:String(data.get('name')).trim(),rating:Number(data.get('rating')),comment:String(data.get('comment')).trim(),photo_path:photoPath,status:'pending'});if(error)throw error;msg.className='form-msg success';msg.textContent='Thank you. Your story has been submitted for review.';form.reset()}catch(e){msg.className='form-msg error';msg.textContent=e.message||'Unable to submit your story.'}}
document.addEventListener('DOMContentLoaded',()=>{initNav();initReveal();initHeroParallax();initStage();bindPricing();loadReviews();document.querySelectorAll('[data-booking-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();submitBooking(f)}));document.querySelectorAll('[data-review-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();submitReview(f)}));document.querySelectorAll('[data-select-package]').forEach(b=>b.addEventListener('click',()=>fillBooking(b.dataset.selectPackage,b.closest('.package-card')?.querySelector('[data-passengers]')?.value||1)))});
